name: Test Product Agent

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test Config Loader
        run: python config_loader.py

      - name: Test Collector
        run: python collector.py "https://shopee.sg/"

      - name: Test URL Resolver
        run: python url_resolver.py <<EOFhttps://s.shopee.sg/2qV98KrxeDEOF
      
      - name: Test Normalizer
        run: python normalizer.py

      - name: Test Validator
        run: python validator.py
